# Title: ApiCurio Registry High Availability based on Postgres Cluster

Environment Setup:

- Crunchy Postgres for Kubernetes: 5.7.0
- Red Hat build of Apicurio Registry: 2.6.5

Prerequisites:

- Install Crunchy Postgres for Kubernetes from OperatorHub
- Install Red Hat build of Apicurio Registry from OperatorHub

# 1. Postgres Cluster Creation:

Create the `source` namespace: `oc new-project source`

Create Kafka clusters using Kafka CR YAML configuration

[source, yaml,indent=0]
----
oc create -f - <<EOF
apiVersion: v1
kind: ConfigMap
metadata:
  name: init-sql
data:
  init.sql: |
    \c apicuriodb
    GRANT CREATE ON SCHEMA public TO "apicuriodb";
EOF
----

[source, yaml,indent=0]
----
oc create -f - <<EOF
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: apicuriodb
spec:
  backups:
    pgbackrest:
      repos:
        - name: repo1
          volume:
            volumeClaimSpec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 1Gi
  databaseInitSQL:
    key: init.sql
    name: init-sql
  instances:
    - dataVolumeClaimSpec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
      name: instance1
      replicas: 2
  port: 5432
  postgresVersion: 16
EOF
----

Extract DB required information from the secret created `mypostgrescluster-pguser-mypostgrescluster` :

[source, yaml,indent=0]
----
echo $(oc get secret apicuriodb-pguser-apicuriodb -o yaml | yq '.data.host') |base64 -d
apicuriodb-primary.source.svc

echo $(oc get secret apicuriodb-pguser-apicuriodb -o yaml | yq '.data.port') |base64 -d
5432

echo $(oc get secret apicuriodb-pguser-apicuriodb -o yaml | yq '.data.dbname') |base64 -d
apicuriodb

echo $(oc get secret apicuriodb-pguser-apicuriodb -o yaml | yq '.data.user') |base64 -d
apicuriodb

echo $(oc get secret apicuriodb-pguser-apicuriodb -o yaml | yq '.data.password') |base64 -d
ut7>xSCgjwK=ZvE)-[i?88a:
----

### 2. Depploy ApiCurio Registry:

Deploy the `ApicurioRegistry CR` in the `source` namespace:

[source, yaml,indent=0]
----
oc create -f - <<EOF
apiVersion: registry.apicur.io/v1
kind: ApicurioRegistry
metadata:
  name: apicurioregistry-psql
  namespace: source
spec:
  configuration:
    persistence: "sql"
    sql:
      dataSource:
        url: "jdbc:postgresql://apicuriodb-primary.source.svc:5432/apicuriodb"
        userName: "apicuriodb"
        password: "ut7>xSCgjwK=ZvE)-[i?88a:"
EOF
----

# 3. Test the High Availability

[source, bash,indent=0]
----
PRIMARY_POD=$(kubectl get pods --selector=postgres-operator.crunchydata.com/role=master -o jsonpath='{.items[*].metadata.labels.postgres-operator\.crunchydata\.com/instance}')
echo $PRIMARY_POD

apicuriodb-instance1-5zx5
----

[source, yaml,indent=0]
----
oc exec -it apicuriodb-instance1-5zx5-0 -n source -- psql -U postgres
Defaulted container "database" out of: database, replication-cert-copy, pgbackrest, pgbackrest-config, postgres-startup (init), nss-wrapper-init (init)
psql (16.4)
Type "help" for help.
postgres=# SELECT pg_is_in_recovery();
 pg_is_in_recovery
-------------------
 f
(1 row)
----

If it returns `true`, you're connected to a standby (read-only) instance.
If it returns `false`, you're on the primary instance.


