# Title: ApiCurio Registry High Availability based on Postgres Cluster

Environment Setup:

- Crunchy Postgres for Kubernetes: 5.7.0
- Red Hat build of Apicurio Registry: 2.6.5

Prerequisites:

- Install Crunchy Postgres for Kubernetes from OperatorHub
- Install Red Hat build of Apicurio Registry from OperatorHub

# 1. Postgres Cluster Creation:

Create the `source` namespace: `oc new-project source`

Create Kafka clusters using Kafka CR YAML configuration

[source, yaml,indent=0]
----
oc create -f - <<EOF
apiVersion: v1
kind: ConfigMap
metadata:
  name: init-sql
data:
  init.sql: |
    \c apicuriodb
    GRANT CREATE ON SCHEMA public TO "apicuriodb";
EOF
----

[source, yaml,indent=0]
----
oc create -f - <<EOF
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: apicuriodb
spec:
  backups:
    pgbackrest:
      repos:
        - name: repo1
          volume:
            volumeClaimSpec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 1Gi
  databaseInitSQL:
    key: init.sql
    name: init-sql
  instances:
    - dataVolumeClaimSpec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
      name: instance1
      replicas: 2
  port: 5432
  postgresVersion: 16
EOF
----

Extract DB required information from the secret created `mypostgrescluster-pguser-mypostgrescluster` :

[source, yaml,indent=0]
----
echo $(oc get secret apicuriodb-pguser-apicuriodb -o yaml | yq '.data.host') |base64 -d
apicuriodb-primary.source.svc

echo $(oc get secret apicuriodb-pguser-apicuriodb -o yaml | yq '.data.port') |base64 -d
5432

echo $(oc get secret apicuriodb-pguser-apicuriodb -o yaml | yq '.data.dbname') |base64 -d
apicuriodb

echo $(oc get secret apicuriodb-pguser-apicuriodb -o yaml | yq '.data.user') |base64 -d
apicuriodb

echo $(oc get secret apicuriodb-pguser-apicuriodb -o yaml | yq '.data.password') |base64 -d
ut7>xSCgjwK=ZvE)-[i?88a:
----

### 2. Depploy ApiCurio Registry:

Deploy the `ApicurioRegistry CR` in the `source` namespace:

[source, yaml,indent=0]
----
oc create -f - <<EOF
apiVersion: registry.apicur.io/v1
kind: ApicurioRegistry
metadata:
  name: apicurioregistry-psql
  namespace: source
spec:
  configuration:
    persistence: "sql"
    sql:
      dataSource:
        url: "jdbc:postgresql://apicuriodb-primary.source.svc:5432/apicuriodb"
        userName: "apicuriodb"
        password: "ut7>xSCgjwK=ZvE)-[i?88a:"
EOF
----

# 3. Test of the Postgres High Availability

Currently, we have two instances, one `primary` and one `standby`:

[source, bash,indent=0]
----
oc get pods
NAME                                                    READY   STATUS      RESTARTS   AGE
apicuriodb-backup-rkwx-fbbf7                            0/1     Completed   0          15m
apicuriodb-instance1-5zx5-0                             4/4     Running     0          2m4s
apicuriodb-instance1-7s4n-0                             4/4     Running     0          15m
apicuriodb-repo-host-0                                  2/2     Running     0          15m
----

First, let's determine which Pod is the primary. If you are using Bash, you can run the following command:

[source, bash,indent=0]
----
kubectl get pods --selector=postgres-operator.crunchydata.com/role=master -o jsonpath='{.items[*].metadata.labels.postgres-operator\.crunchydata\.com/instance}'
apicuriodb-instance1-5zx5
----

We can use the value above to delete the StatefulSet associated with the current Postgres primary instance.

[source, bash,indent=0]
----
kubectl delete sts apicuriodb-instance1-5zx5
----

Let's see what happens. Try getting all of the StatefulSets for the Postgres instances in the `apicuriodb` cluster:

[source, bash,indent=0]
----
apicuriodb-instance1-5zx5-0                             0/4     Running     0          2m4s
apicuriodb-instance1-7s4n-0                             4/4     Running     0          15m
----

The apicurio pod shows the following:

[source, bash,indent=0]
----
apicurioregistry-psql-deployment-565f9588bc-2sn6m registry 2024-10-31 09:07:20 WARN <_> [io.quarkus.agroal.runtime.AgroalEventLoggingListener] (executor-thread-14) Datasource '<default>': This connection has been closed.
apicurioregistry-psql-deployment-565f9588bc-2sn6m registry 2024-10-31 09:07:20 WARN <_> [io.apicurio.registry.metrics.health.liveness.PersistenceExceptionLivenessCheck] (executor-thread-14) Liveness problem suspected in PersistenceExceptionLivenessCheck because of an exception: : io.apicurio.registry.storage.RegistryStorageException: io.apicurio.registry.storage.impl.sql.jdb.RuntimeSqlException: org.postgresql.util.PSQLException: FATAL: terminating connection due to administrator command

2024-10-31 09:07:27 INFO <> [io.apicurio.registry.metrics.health.liveness.PersistenceExceptionLivenessCheck] (executor-thread-26) After this event, the error counter is 2 (out of the maximum 5 allowed).
2024-10-31 09:07:37 INFO <_> [io.apicurio.registry.metrics.health.liveness.PersistenceExceptionLivenessCheck] (executor-thread-25) After this event, the error counter is 5 (out of the maximum 5 allowed).
apicurioregistry-psql-deployment-565f9588bc-2sn6m registry 2024-10-31 09:07:48 WARN <> [io.quarkus.agroal.runtime.AgroalEventLoggingListener] (agroal-11) Datasource '<default>': Closing connection in incorrect state VALIDATION
apicurioregistry-psql-deployment-565f9588bc-2sn6m registry 2024-10-31 09:07:48 INFO <> [io.quarkus.bootstrap.runner.Timing] (Shutdown thread) apicurio-registry-storage-sql stopped in 0.030s
----

NOTE: The apicurio registry pod exhausted all the retries of the liveness Persistence Check and restart the process that connect again to the primary instance.


The new primary instance is:

[source, yaml,indent=0]
----
kubectl get pods --selector=postgres-operator.crunchydata.com/role=master -o jsonpath='{.items[*].metadata.labels.postgres-operator\.crunchydata\.com/instance}'
apicuriodb-instance1-7s4n
----


[source, yaml,indent=0]
----
oc exec -it apicuriodb-instance1-7s4n-0 -n source -- psql -U postgres
Defaulted container "database" out of: database, replication-cert-copy, pgbackrest, pgbackrest-config, postgres-startup (init), nss-wrapper-init (init)
psql (16.4)
Type "help" for help.
postgres=# SELECT pg_is_in_recovery();
 pg_is_in_recovery
-------------------
 f
(1 row)
----

If it returns `true`, you're connected to a standby (read-only) instance.
If it returns `false`, you're on the primary instance.
